[package]
name = "al"
version = "0.1.5"
authors = ["Christopher Sebastian <csebastian3@gmail.com>"]
license = "MIT"
repository = "https://github.com/likebike/fasteval"
description = """Renamed to 'fasteval'."""
edition = "2018"

[dependencies]

[features]

